Document: sidux-art-wallpaper
Title: Debian sidux-art-wallpaper Manual
Author: <insert document author here>
Abstract: This manual describes what sidux-art-wallpaper is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sidux-art-wallpaper/sidux-art-wallpaper.sgml.gz

Format: postscript
Files: /usr/share/doc/sidux-art-wallpaper/sidux-art-wallpaper.ps.gz

Format: text
Files: /usr/share/doc/sidux-art-wallpaper/sidux-art-wallpaper.text.gz

Format: HTML
Index: /usr/share/doc/sidux-art-wallpaper/html/index.html
Files: /usr/share/doc/sidux-art-wallpaper/html/*.html

  
